name: Database Migration Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'migrations/**'
      - 'models/**'
      - 'tests/**'
      - 'scripts/**'
      - 'package.json'
      - '.github/workflows/database-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'migrations/**'
      - 'models/**'
      - 'tests/**'
      - 'scripts/**'
      - 'package.json'
      - '.github/workflows/database-tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create .env.test file
      run: |
        echo "SUPABASE_URL=$SUPABASE_URL" > .env.test
        echo "SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY" >> .env.test
        echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env.test
    
    - name: Run migration
      run: npm run migrate
    
    - name: Install test helpers
      run: npm run migrate:test
    
    - name: Run tests
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage
        fail_ci_if_error: true
